Add support for BIOS
Most of the procedure is the same. But unlike UEFI, where grub-install
can determine the disk containing the EFI System Partition (ESP) based
on what's mounted at /boot/efi, on BIOS the user needs to tell us
which disk is the boot disk (which disk the BIOS will load the master
boot record from). Then, instead of copying the generated core image
to the ESP, on BIOS the core image is copied to /boot/grub/i386-pc and
then has to be installed from there to the boot disk (either to a BIOS
Boot partition on GPT, or embedded in the "gap" on MBR). The
grub-setup-bios utility exists for doing that installation.

diff --git a/grub-luks2-install b/grub-luks2-install
--- a/grub-luks2-install
+++ b/grub-luks2-install
@@ -1,5 +1,5 @@
 #!/bin/bash
-# Copyright 2022 Dan Moulding
+# Copyright 2022-2023 Dan Moulding
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -23,6 +23,13 @@ function add_mod()
     fi
 }
 
+function blockdev_type()
+{
+    local dev=${1}
+
+    lsblk --nodeps --noheadings --output TYPE "${dev}"
+}
+
 function mod_added()
 {
     local mod=${1}
@@ -41,13 +48,18 @@ function on_exit()
     if [[ -n "${config}" ]]; then
         rm -f "${config}"
     fi
-    if [[ -n "${log}" ]]; then
-        rm -f "${log}"
+    if [[ -n "${gi_log}" ]]; then
+        rm -f "${gi_log}"
+    fi
+    if [[ -n "${gbs_log}" ]]; then
+        rm -f "${gbs_log}"
     fi
     for ((i = ${#mounted[@]} - 1; i >= 0; --i)); do
         umount "${mounted[i]}"
     done
 }
+
+firmware=
 
 trap on_exit EXIT
 
@@ -61,9 +73,29 @@ if [[ "$(uname -m)" != x86_64 ]]; then
     exit 1
 fi
 
-if [[ ! -d /sys/firmware/efi ]]; then
-    echo "This script is designed to install GRUB on UEFI systems only." >&2
-    exit 1
+if [[ -d /sys/firmware/efi ]]; then
+    firmware=uefi
+else
+    firmware=bios
+    boot_disk=${1}
+    if [[ -z "${boot_disk}" ]]; then
+        echo "This system uses BIOS firmware. Please specify the boot disk." >&2
+        echo "The boot disk is the disk the BIOS will load the master boot" >&2
+        echo "record from. This is often, but not always, the same disk" >&2
+        echo "that contains the volume containing /boot." >&2
+        exit 1
+    fi
+    if [[ ! -b "${boot_disk}" ]]; then
+        echo "${boot_disk} is not a valid block device." >&2
+        exit 1
+    fi
+    if [[ "$(blockdev_type "${boot_disk}")" != disk ]]; then
+        echo "${boot_disk} does not appear to be a regular disk device." >&2
+        read -p "Continue? : "
+        if [[ "${REPLY}" != y ]]; then
+            exit 1
+        fi
+    fi
 fi
 
 if mountpoint /boot &> /dev/null; then
@@ -84,15 +116,17 @@ else
     fi
 fi
 
-if ! mountpoint /boot/efi &> /dev/null; then
-    if mount /boot/efi; then
-        mounted+=(/boot/efi)
-    else
-        echo "Nothing mounts at /boot/efi. This must be a misconfiguration" >&2
-        echo "(unless your entire root file system is on the EFI system" >&2
-        echo "partition [ESP] which would be highly unusual). The ESP" >&2
-        echo "must be mounted or the core image cannot be installed." >&2
-        exit 1
+if [[ "${firmware}" == uefi ]]; then
+    if ! mountpoint /boot/efi &> /dev/null; then
+        if mount /boot/efi; then
+            mounted+=(/boot/efi)
+        else
+            echo "Nothing mounts at /boot/efi. This must be a misconfiguration" >&2
+            echo "(unless your entire root file system is on the EFI system" >&2
+            echo "partition [ESP] which would be highly unusual). The ESP" >&2
+            echo "must be mounted or the core image cannot be installed." >&2
+            exit 1
+        fi
     fi
 fi
 
@@ -101,6 +135,7 @@ bootdev=$(awk -v bootmnt="${bootmnt}" \
           /proc/self/mounts)
 if [[ -z "${bootdev}" ]]; then
     echo "Failed to determine which device is the boot device." >&2
+    echo "The boot device is the volume containing /boot." >&2
     read -p "Enter the name of the boot device (e.g. /dev/sda1): "
     bootdev=${REPLY}
     if [[ ! -b "${bootdev}" ]]; then
@@ -146,6 +181,10 @@ cipher=$(awk '$1 == "Cipher:" { print $2; exit }' <<< "${output}")
 hash=$(awk '$1 == "Hash:" { print $2; exit }' <<< "${output}")
 pbkdf=$(awk '$1 == "PBKDF:" { print $2; exit }' <<< "${output}")
 
+echo "Firmware        : ${firmware^^}"
+if [[ "${firmware}" == bios ]]; then
+    echo "Boot disk       : ${boot_disk}"
+fi
 echo "Boot mountpoint : ${bootmnt}"
 echo "Boot device     : ${bootdev}"
 echo "Boot device type: ${devtype}"
@@ -171,27 +210,40 @@ if [[ "${pbkdf}" != pbkdf2 ]]; then
 fi
 
 # grub-install needs to be run to copy the modules and other files
-# (fonts, locales, themes, etc.) to the boot volume. It also will
-# create the required directory structure on the EFI system partition
-# and set the EFI NVRAM variables via efibootmgr. We also run it in
-# verbose mode and then glean from the log which modules it would have
-# included (which won't include any of the LUKS modules), so that we
-# know what modules in addition to the LUKS modules we should include.
-if ! log=$(mktemp grub-install.log.XXXX); then
+# (fonts, locales, themes, etc.) to the boot volume. On UEFI it also
+# will create the required directory structure on the EFI system
+# partition and set the EFI NVRAM variables via efibootmgr. We also
+# run it in verbose mode and then glean from the log which modules it
+# would have included (which won't include any of the LUKS modules),
+# so that we know what modules in addition to the LUKS modules we
+# should include.
+if ! gi_log=$(mktemp grub-install.log.XXXX); then
     exit 1
 fi
 echo -n "Running grub-install... "
-if ! grub-install --verbose &> "${log}"; then
+args=(--verbose)
+if [[ "${firmware}" == bios ]]; then
+    args+=("${boot_disk}")
+fi
+if ! grub-install "${args[@]}" &> "${gi_log}"; then
     echo "FAILED."
     echo ""
-    mv "${log}" grub-install.log
+    mv "${gi_log}" grub-install.log
     chmod a+r grub-install.log
     echo "grub-install failed. Check grub-install.log for reason." >&2
     exit 1
 fi
 echo "done."
 
-mods=($(grep -o 'reading.*[.]mod' "${log}" | sort -u |
+if [[ "${firmware}" == bios ]]; then
+    boot_image=/boot/grub/i386-pc/boot.img
+    if [[ ! -f "${boot_image}" ]]; then
+        echo "grub-install succeeded, but ${boot_image} is missing." >&2
+        exit 1
+    fi
+fi
+
+mods=($(grep -o 'reading.*[.]mod' "${gi_log}" | sort -u |
         awk '{ gsub(/.*\/|[.]mod/, "", $2); print $2 }'))
 
 # grub-install will have failed to detect anything beyond the LUKS
@@ -324,12 +376,16 @@ case "${pbkdf}" in
         ;;
 esac
 
-# We can also glean from the log where grub-install wants the core
-# image to be output.
-image=$(awk '/copying.*\/boot\/grub\/x86_64-efi\/core.efi/ {
-        gsub(/[`'"'"']|[.]$/, "", $NF); print $NF; exit }' "${log}")
+if [[ "${firmware}" == uefi ]]; then
+    # We can also glean from the log where grub-install wants the core
+    # image to be output.
+    image=$(awk '/copying.*\/boot\/grub\/x86_64-efi\/core.efi/ {
+        gsub(/[`'"'"']|[.]$/, "", $NF); print $NF; exit }' "${gi_log}")
 
-echo "Core image is ${image}"
+    echo "Core image is ${image}"
+else
+    image=/boot/grub/i386-pc/core.img
+fi
 
 # GRUB will load the "normal" module after executing any embedded
 # configuration, so the only thing we need to do in our embedded
@@ -338,9 +394,18 @@ echo "Core image is ${image}"
 config=$(mktemp grub.cfg.XXXX)
 echo "cryptomount -u ${uuid//-/}" > "${config}"
 
-opts+=(-c "${config}")
+case "${firmware}" in
+    bios) format=i386-pc;;
+    uefi) format=x86_64-efi;;
+    *)
+        echo "Unhandled firmware type: ${firmware}"
+        exit 1
+        ;;
+esac
+
+opts=(-c "${config}")
 opts+=(-o "${image}")
-opts+=(-O x86_64-efi)
+opts+=(-O "${format}")
 opts+=(-p "${prefix}")
 
 output=$(grub-mkimage "${opts[@]}" "${mods[@]}" 2>&1)
@@ -350,6 +415,25 @@ if [[ "${?}" -ne 0 ]]; then
 fi
 echo "Wrote new core image with the following modules:"
 echo "${mods[*]}"
+
+if [[ "${firmware}" == bios ]]; then
+    if ! gbs_log=$(mktemp grub-bios-setup.log.XXXX); then
+        exit 1
+    fi
+    echo -n "Installing core image to ${boot_disk}... "
+    opts=(--boot-image="${boot_image#/boot/grub}")
+    opts+=(--core-image="${image#/boot/grub}")
+    if ! grub-bios-setup "${opts[@]}" "${boot_disk}" &> "${gbs_log}"
+    then
+        echo "FAILED."
+        echo ""
+        mv "${gbs_log}" grub-bios-setup.log
+        chmod a+r grub-bios-setup.log
+        echo "grub-bios-setup failed. Check grub-bios-setup.log for reason." >&2
+        exit 1
+    fi
+    echo "done."
+fi
 
 exit 0
 
